### ISSUE TITLE
How do I access the posts.json file

### ISSUE THREAD

**Issue by monish-atom** [maxnowack/signaldb#675]
``ts
export const posts = new Collection({
	persistence: createFilesystemAdapter('./collections/posts.json'),
	reactivity: reactivityAdapter,
});
``
I'm using solidjs and I don't know if I can access the file or not.

**Comment by maxnowack** [comment]
Hey @monish-atom, if you want to use SignalDB in the browser, you can't use the filesystem persistence adapter because it requires access to the filesystem via the `fs` module (which is not available in the browser context). You can use the local storage persistence adapter instead.
If you're in a node.js environment, the posts.json file is located in the specified path. Ensuring sufficient permissions on this file is out of the scope of SignalDB.

**Comment by monish-atom** [comment]
Thanks for the help.
