### ISSUE TITLE
SyncManager(suggestion): add upsert setup

### ISSUE THREAD

**Issue by Cmacu** [maxnowack/signaldb#932]
## Description
We have a basic sync setup with push, pull and registerRemoteChange. The backend exclusively accepts and sends added, modified and removed and uses web sockets to send changes.

## Problem
When we create a new record it's pushed as added. The web socket sends onChange event to all clients, which triggers pull. The pull sends the record in the added list. This results in an error since the record already exists on the client it was created (the other clients work as expected).

## Workarounds

- Catch the error and manually update the timestamp to ignore/bypass the created record for future syncs. Note that this introduces a risk of missing/skipping other updates.

- Create unique web socket client ids. And send them with push as well as onChange so the changes can be ignored if the receiving client is the same as the originating one. Note this can't be based on userId/session because a given user can have multiple clients

- in the pull check if each of the added record exists in the client storage and ignore it if it does. The issue with this solution is that it adds a lot of overhead for other clients.

## Suggested solutions:

- implement upsert instead of update and create. This would resolve the issue since it would ignore the duplicate. Not sure how I feel about the chances of a real collision where 2 unique records have the same id. I think this scenario would actually be a backend issue because the records need to be pushed somehow before they are pulled

- another strategy could be keeping a temporary list of added ids between the push and pull where if the next pull returns them as added, they are ignored 

## Other notes:

- similar issue exists for removed, where a record is removed from the client and received by the following pull in the removed list

- there could be other possible devland implementations where multiple/separate client and server ids are used, but I would stay away from these due to complexity issues

- maybe I am missing something? Some further guidance and docs on your thoughts on setting up backend servers can be very useful for me and probably for other people working on this. Maybe even considering examples with common backend sync implementations in various languages/frameworks could be a good idea? I can help with setting up NodeJs/Express, NodeJS/Nest, PHP/Laravel, .Net/ASP examples given your help and guidance.

**Comment by obedm503** [comment]
Had the same issue with the `ReplicatedCollection` a few months ago. See #792

The fix was to implement upserts (#794). I'm surprised that the fix does not work with the new `SyncManager`

**Comment by Cmacu** [comment]
@obedm503 thanks for the feedback. Maybe I am doing something wrong. I will review and hopefully we can also make it work.

**Comment by maxnowack** [comment]
I think we also have to implement upserts for the `SyncManager` to keep implementation easy. I'll work on it later this day 🙂

**Comment by maxnowack** [comment]
> * implement upsert instead of update and create. This would resolve the issue since it would ignore the duplicate. Not sure how I feel about the chances of a real collision where 2 unique records have the same id. I think this scenario would actually be a backend issue because the records need to be pushed somehow before they are pulled

With #940 I'm now using upsert-like behavior internally. I don't think that we really have to care about id-collisions during sync on client side as they would be many other issues before that point.

> * another strategy could be keeping a temporary list of added ids between the push and pull where if the next pull returns them as added, they are ignored

I'm using this strategy currently to distinguish between changes to the collection that are due to sync and all other changes. I think in this case, using an upsert-like approach is better.

> * similar issue exists for removed, where a record is removed from the client and received by the following pull in the removed list

In this case nothing happens as there won't be an error when a selector didn't match any items in a `removeOne`/`removeMany`. In #940 I also took care of updates that are made on non-existing items and create them.

> * there could be other possible devland implementations where multiple/separate client and server ids are used, but I would stay away from these due to complexity issues

We're currently using this approach at VineForecast. I strongly advise to avoid separate client and server ids. Besides the added complexity,  there are many other issues that can occur (like duplicate inserts on backend side of a push wasn't recognized as successful on client side; depending on the specific implementation).

> * maybe I am missing something? Some further guidance and docs on your thoughts on setting up backend servers can be very useful for me and probably for other people working on this. Maybe even considering examples with common backend sync implementations in various languages/frameworks could be a good idea? I can help with setting up NodeJs/Express, NodeJS/Nest, PHP/Laravel, .Net/ASP examples given your help and guidance.

This would help a lot! Feel free to contribute. We could integrate it in text form in the documentation (like the existing guides), as code in the examples folder or even in a separate repository and just put a link to it in the documentation. But I'm also open for complete different ideas 🙂
